FIXED ERROR in src/app/datatable/data-table.component.html(3,13): : Property 'configService' is private and only accessible within class 'DataTableComponent'. src/app/datatable/data-table.component.html(3,13): : Property 'configService' is private and only accessible within class 'DataTableComponent'. src/app/datatable/data-table.component.html(119,13): : Property 'configService' is private and only accessible within class 'DataTableComponent'. src/app/datatable/data-table.component.html(355,13): : Property 'configService' is private and only accessible within class 'DataTableComponent'. src/app/datatable/data-table.component.html(355,13): : Property 'configService' is private and only accessible within class 'DataTableComponent'. src/app/datatable/data-table.component.html(475,21): : Property 'dataService' is private and only accessible within class 'DataTableComponent'. src/app/datatable/data-table.component.html(504,21): : Property 'dataService' is private and only accessible within class 'DataTableComponent'. src/app/datatable/data-table.component.html(546,10): : Property 'configService' is private and only accessible within class 'DataTableComponent'. src/app/datatable/data-table.component.html(557,10): : Property 'configService' is private and only accessible within class 'DataTableComponent'. src/app/datatable/data-table.component.html(618,49): : Property 'configService' is private and only accessible within class 'DataTableComponent'. src/app/datatable/data-table.component.html(625,21): : Property 'configService' is private and only accessible within class 'DataTableComponent'. src/app/tabs/tabs.component.html(2,6): : Property 'configService' is private and only accessible within class 'TabsComponent'. src/app/tabs/tabs.component.html(10,79): : Property 'configService' is private and only accessible within class 'TabsComponent'. src/app/tabs/tabs.component.html(39,6): : Property 'configService' is private and only accessible within class 'TabsComponent'. src/app/tabs/tabs.component.html(39,6): : Property 'configService' is private and only accessible within class 'TabsComponent'. src/app/exporter/exporter.component.html(25,54): : Property 'currentDropdown' does not exist on type 'ExporterComponent'. src/app/exporter/exporter.component.html(84,54): : Property 'currentDropdown' does not exist on type 'ExporterComponent'. src/app/exporter/exporter.component.html(175,56): : Property 'currentDropdown' does not exist on type 'ExporterComponent'. src/app/exporter/exporter.component.html(245,60): : Property 'currentDropdown' does not exist on type 'ExporterComponent'. src/app/exporter/exporter.component.html(20,22): : Property 'currentDropdown' does not exist on type 'ExporterComponent'. src/app/exporter/exporter.component.html(20,22): : Property 'currentDropdown' does not exist on type 'ExporterComponent'. src/app/exporter/exporter.component.html(79,22): : Property 'currentDropdown' does not exist on type 'ExporterComponent'. src/app/exporter/exporter.component.html(79,22): : Property 'currentDropdown' does not exist on type 'ExporterComponent'. src/app/exporter/exporter.component.html(169,22): : Property 'currentDropdown' does not exist on type 'ExporterComponent'. src/app/exporter/exporter.component.html(169,22): : Property 'currentDropdown' does not exist on type 'ExporterComponent'. src/app/exporter/exporter.component.html(169,22): : Property 'continue' does not exist on type 'ExporterComponent'. src/app/exporter/exporter.component.html(240,22): : Property 'currentDropdown' does not exist on type 'ExporterComponent'. src/app/exporter/exporter.component.html(240,22): : Property 'currentDropdown' does not exist on type 'ExporterComponent'.