FIX ERROR in src/app/datatable/data-table.component.html(475,21): : Property 'dataService' is private and only accessible within class 'DataTableComponent'. src/app/datatable/data-table.component.html(504,21): : Property 'dataService' is private and only accessible within class 'DataTableComponent'. src/app/exporter/exporter.component.html(25,54): : Property 'currentDropdown' does not exist on type 'ExporterComponent'.
renamed  ngIf="currentDropdown  to ngIf="dropdown